export const NODE_CONFIG = 'NODE_CONFIG'
export const COMMIT_NODE_CONFIG = 'workflow/NODE_CONFIG'

export const FLOW_PERMISSION = 'SET_FLOW_PERMISSION'
export const COMMIT_FLOW_PERMISSION = 'workflow/SET_FLOW_PERMISSION'

export const FORM_PROPERTY_LIST = 'FORM_PROPERTY_LIST'
export const COMMIT_FORM_PROPERTY_LIST = 'workflow/FORM_PROPERTY_LIST'

export const USER_IDS = 'USER_IDS'
export const COMMIT_USER_IDS = 'workflow/USER_IDS'


export const ALREADY_CONDITION = 'ALREADY_CONDITION'
export const COMMIT_ALREADY_CONDITION = 'workflow/ALREADY_CONDITION'
